export default {
  GET_NEW_ITEM_BY_GRAB_LIMIT: 1,
  GET_NEW_ITEM_BY_ORDER_BY: 2,
  GRAB_LIMIT_TO_FIRST: 1,
  GRAB_LIMIT_TO_LAST: 2,
  ENABLE_NOTIFICATION: true,
  AUTO_CLOSE_NOTIFICATION: false,
  CLOSE_NOTIFICATION_TIMEOUT: 3000
};
